### ISSUE TITLE
404 link on docs website

### ISSUE THREAD

**Issue by maelle** [erikaris/rplaywright#3]
First of all congrats on such a cool project! :star_struck: 

Then, I got a 404 for https://erikaris.github.io/rplaywright/articles/rplaywright-setup.html (Setup link in the navbar)

**Comment by erikaris** [comment]
Hi Maelle, 
Thank you for the kind words. I am glad you like the project. 
About the broken link, please check [https://erikaris.github.io/rplaywright/articles/rplaywright.html](https://erikaris.github.io/rplaywright/articles/rplaywright.html) for the updated setup article. 

Please let me know if it works for you now.

**Comment by maelle** [comment]
thank you, yes it now works!
